### ISSUE TITLE
how to use @flow.flow_start_view in viewflow

### ISSUE THREAD

**Issue by bobowang2017** [kmmbvnr/viewflow-intro#1]
Hello, I want to use @flow.flow_start_view in viewflow decorator to replace the viewflow.flow.views.CreateProcessView and add my logic code in method, how to do it ? Thank you

**Comment by kmmbvnr** [comment]
Here is the cookbook sample of custom views - 
 https://github.com/viewflow/cookbook/tree/master/custom_views
